### ISSUE TITLE
Synology EDS14

### ISSUE THREAD

**Issue by schneiderkh** [jishi/node-sonos-web-controller#24]
Hi,
I try to install the songs-web-controller on a EDS14 with the node-package from Synology.

One thing I change per hand:
In "/etc/profile"   I put   "/volume1/@appstore/Node.js/usr/bin:$PATH:/bin:"   in Path

PATH=/volume1/@appstore/Node.js/usr/bin:$PATH:/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
export PATH

Problem :

DS-EDS14> node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'node-static'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/volumeUSB1/usbshare1-1/@sharebin/web/sonos/server.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
DS-EDS14> 

I need help :-(

Karl-Heinz Schneider
Germany

**Comment by jishi** [comment]
You haven't fixed the dependencies. You need to invoke

npm install

To download the necessary modules first.

**Comment by schneiderkh** [comment]
It works - Great

Do you now why the Web-page look "a bit" different on a a iPad1 (IOS 5) ?

But it works good on iPad1 !  Now the old iPad can stay alive :-)

**Comment by jishi** [comment]
Well, the web interface was primarily developed for late versions of Chrome and Firefox. I know Safari struggles a bit with some of the calc() css that I use, especially the older versions. 

The web interface wasn't really planned to be used by touch devices, and I have been working on a touch-friendly version (similar to the official mobile app) but it's far from finished (and I have limited time right now). You will need to be patient.
