### ISSUE TITLE
ERR_INVALID_CALLBACK on clean clone, npm install, then run

### ISSUE THREAD

**Issue by jzajac2** [jishi/node-sonos-web-controller#67]
just forked, cloned, deployed to my pi box however getting this after a few seconds. see node version at bottom - any other info you need?

```
pi@rpi3:~/code/node-sonos-web-controller $ node server.js
no settings file found, will only use default settings
http server listening on port 8080
queue-changed Master Bathroom
fetching album art from undefined
fetching album art from undefined
fetching album art from undefined
fetching album art from undefined
fetching album art from undefined
fetching album art from undefined
200
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.exists (fs.js:197:3)
    at ClientRequest.<anonymous> (/home/pi/code/node-sonos-web-controller/server.js:58:19)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
pi@rpi3:~/code/node-sonos-web-controller $ node -v
v10.15.2
pi@rpi3:~/code/node-sonos-web-controller $ npm -v
6.11.3

```

**Comment by miamijerry** [comment]
I was able to get around this "ERR_INVALID_CALLBACK" error by using
 node-v8.11.3-x64
