### ISSUE TITLE
Error after seconds

### ISSUE THREAD

**Issue by dannymertens** [jishi/node-sonos-web-controller#68]
I go to the site, see the interface and then its crashes 

pi@raspibureau:~/Documents/Sonos $ node server.js
no settings file found, will only use default settings
http server listening on port 8080
fetching album art from undefined
fetching album art from undefined
fetching album art from undefined
fetching album art from undefined
fetching album art from undefined
fetching album art from undefined
200
fs.js:135
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.exists (fs.js:199:3)
    at ClientRequest.<anonymous> (/home/pi/Documents/Sonos/server.js:58:19)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at Socket.socketOnData (_http_client.js:456:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12) {
  code: 'ERR_INVALID_CALLBACK'
}
pi@raspibureau:~/Documents/Sonos $

**Comment by miamijerry** [comment]
Try earlier version of nodejs, like node-v8.11.3-x64
Worked for me.

**Comment by puzio0** [comment]
I am having the same issue.  On node v10.  Will try to downgrade and test.

**Comment by puzio0** [comment]
This worked.  Thank you.  Running V8.11.3 and it's working.
